name: PushHFspace
on:
  push:
    branches:
      - main
    paths:
      - 'Script/Data/1-2025results.txt'
      - 'Script/Data/2-2025results.txt'
      - 'Script/Data/5-2025results.txt'

jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          git config --global user.name "Rokate"
          git config --global user.email "77772464+Rokate@users.noreply.github.com"

          echo "machine huggingface.co login $HF_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git clone https://huggingface.co/spaces/Keron/xamdata hf-repo
          
          mkdir -p hf-repo/data
          cp Script/Data/1-2025results.txt hf-repo/data/
          cp Script/Data/2-2025results.txt hf-repo/data/
          cp Script/Data/5-2025results.txt hf-repo/data/
          
          cd hf-repo
          git add data/1-2025results.txt data/2-2025results.txt data/5-2025results.txt
          git commit -m "Update results files from GitHub Actions"
          
          git push https://$HF_TOKEN@huggingface.co/spaces/Keron/xamdata main
